name: Build

on:
  workflow_call:
    inputs:
      version:
        type: string
        required: true

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

      - name: Generate test data
        run: |
          echo "Hello" > result.txt
          tar -cz result.txt -f result-${{inputs.version}}.tar.gz

      - name: Upload data artifacts
        uses: actions/upload-artifact@v2
        with:
          name: result
          path: |
            *.tar.gz
