name: Pull request
on:
  pull_request:
jobs:

  prepare:
    name: Prepare
    uses: ./.github/workflows/prepare.yml
    with:
      verify_tag: false

  build:
    name: Build
    needs: prepare
    uses: ./.github/workflows/build.yml
    with:
      version: pr${{github.event.number}}-${{needs.prepare.outputs.version}}