name: Prepare

on:
  workflow_call:
    inputs:
      verify_tag:
        type: boolean
        required: true
    outputs:
      version:
        value: ${{ jobs.prepare.outputs.version }}

jobs:
  prepare:
    name: Prepare Source
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.verify_tag.outcome == 'success' && steps.version.outputs.version || steps.version.outputs.sha }}
    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Get version
        id: version
        run: |
          echo "::set-output name=version::$(awk '/version:/ {print $2}' metadata.yaml)"
          echo "::set-output name=sha::$(git rev-parse --short HEAD)"

      - name: Check release tag
        id: verify_tag
        if: inputs.verify_tag
        run: |
          test refs/tags/${{ steps.version.outputs.version }} == ${{ github.ref }}
          git branch --contains ${{ steps.version.outputs.version }} | grep ^..${{ github.event.repository.default_branch }}
